#!/bin/sh

# Check if curl and wget installed
if ! which wget > /dev/null && which curl > /dev/null ; then
    echo "wget or curl not installed $0"
fi

# Copy config file to the right place
if ! which bitsnet > /dev/null ; then
    cp ./bitsnetrc ~/.bitsnetrc
fi

# Copy the script to executables
if [ ! -d ~/.local/lib/bitsnet ]; then
    mkdir ~/.local/lib/bitsnet
fi
cp ./util.sh ~/.local/lib/bitsnet/util.sh
cp ./bitsnet ~/.local/bin/bitsnet

# Create a desktop file
cp ./bitsnet.desktop ~/.local/share/applications/bitsnet.desktop

# Create a man page
# To Be Done
