#!/bin/sh

# Copy config file to the right place
cp ./bitsnetrc ~/.bitsnetrc

# Copy the script to executables
if [ ! -d ~/.local/lib/bitsnet ]; then
    mkdir ~/.local/lib/bitsnet
fi
cp ./util.sh ~/.local/lib/bitsnet/util.sh
cp ./bitsnet ~/.local/bin/bitsnetTwo

# Create a desktop file
cp ./bitsnet.desktop ~/.local/share/applications/bitsnet.desktop

# Create a man page
# To Be Done
